services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
    command: npm run dev
  
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm start
